-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 22:25:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fast_shopping
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fast_shopping
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fast_shopping` DEFAULT CHARACTER SET utf8 ;
USE `fast_shopping` ;

-- -----------------------------------------------------
-- Table `fast_shopping`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fast_shopping`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast_shopping`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fast_shopping`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unit_price` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_categories_idx` (`categories_id` ASC),
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`categories_id`)
    REFERENCES `fast_shopping`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast_shopping`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fast_shopping`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast_shopping`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fast_shopping`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_customers1_idx` (`customers_id` ASC),
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `fast_shopping`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast_shopping`.`products_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fast_shopping`.`products_order` (
  `id` INT NOT NULL,
  `quantity` VARCHAR(45) NULL,
  `products_id` INT NOT NULL,
  `orders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_order_products1_idx` (`products_id` ASC),
  INDEX `fk_products_order_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_products_order_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `fast_shopping`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_order_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `fast_shopping`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
