-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 23:40:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fast_shopping
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fast_shopping
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fast_shopping` DEFAULT CHARACTER SET utf8 ;
USE `fast_shopping` ;

-- -----------------------------------------------------
-- Table `fast_shopping`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fast_shopping`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast_shopping`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fast_shopping`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unit_price` INT NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `thumbnail` VARCHAR(255) NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_categories_idx` (`categories_id` ASC),
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`categories_id`)
    REFERENCES `fast_shopping`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast_shopping`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fast_shopping`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast_shopping`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fast_shopping`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_customers1_idx` (`customers_id` ASC),
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `fast_shopping`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fast_shopping`.`products_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fast_shopping`.`products_order` (
  `id` INT NOT NULL,
  `quantity` VARCHAR(45) NULL,
  `products_id` INT NOT NULL,
  `orders_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_order_products1_idx` (`products_id` ASC),
  INDEX `fk_products_order_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_products_order_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `fast_shopping`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_order_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `fast_shopping`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `fast_shopping`.`categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `fast_shopping`;
INSERT INTO `fast_shopping`.`categories` (`id`, `slug`, `name`) VALUES (1, 'tech', 'Technology');
INSERT INTO `fast_shopping`.`categories` (`id`, `slug`, `name`) VALUES (2, 'shoes', 'Shoes');
INSERT INTO `fast_shopping`.`categories` (`id`, `slug`, `name`) VALUES (3, 'toys', 'Toys');
INSERT INTO `fast_shopping`.`categories` (`id`, `slug`, `name`) VALUES (4, 'home', 'Home');

COMMIT;


-- -----------------------------------------------------
-- Data for table `fast_shopping`.`products`
-- -----------------------------------------------------
START TRANSACTION;
USE `fast_shopping`;
INSERT INTO `fast_shopping`.`products` (`id`, `unit_price`, `name`, `description`, `thumbnail`, `categories_id`) VALUES (1, 542.99, 'Samsung Galaxy Note 10+ Plus Factory Unlocked Cell', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', NULL, 1);
INSERT INTO `fast_shopping`.`products` (`id`, `unit_price`, `name`, `description`, `thumbnail`, `categories_id`) VALUES (2, 89.99, 'Acer SB22Q bi 21.5 inches Full HD (1920 x 1080) IPS', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', NULL, 1);
INSERT INTO `fast_shopping`.`products` (`id`, `unit_price`, `name`, `description`, `thumbnail`, `categories_id`) VALUES (3, 16.99, 'Disney Pixar Toy Story 4 Blast-Off Buzz Lightyear Figure', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', NULL, 3);
INSERT INTO `fast_shopping`.`products` (`id`, `unit_price`, `name`, `description`, `thumbnail`, `categories_id`) VALUES (4, 189.00, 'DeskCycle Under Desk Cycle Pedal Exerciser - Stationary Mini', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', NULL, 2);
INSERT INTO `fast_shopping`.`products` (`id`, `unit_price`, `name`, `description`, `thumbnail`, `categories_id`) VALUES (5, 187.99, 'Portable Monitor - 15.6-Inch USB-C Portable Display, 1080P Full HD', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', NULL, 1);
INSERT INTO `fast_shopping`.`products` (`id`, `unit_price`, `name`, `description`, `thumbnail`, `categories_id`) VALUES (6, 101.50, 'Adidas Men\'s Tech Response Golf Shoes', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', NULL, 2);
INSERT INTO `fast_shopping`.`products` (`id`, `unit_price`, `name`, `description`, `thumbnail`, `categories_id`) VALUES (7, 55.99, 'Sainless Steel Knife Set With Block', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', NULL, 2);
INSERT INTO `fast_shopping`.`products` (`id`, `unit_price`, `name`, `description`, `thumbnail`, `categories_id`) VALUES (8, 29.97, 'Car Vacuum, HOTOR Corded Car Vacuum Cleaner', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', NULL, 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fast_shopping`.`customers`
-- -----------------------------------------------------
START TRANSACTION;
USE `fast_shopping`;
INSERT INTO `fast_shopping`.`customers` (`id`, `fullname`, `phone`, `address`, `email`) VALUES (1, 'Jhon Doe', '000 00 00', 'Main Street, #100-200, Wonderland', 'jhondoe@email.com');

COMMIT;

